#
# @info Default page statuses
# @path site/blueprints/statuses/default.yml
# @date 20220707
#

draft:
  label: Entwurf
  text: Inhalte können nur von dir angesehen werden.
unlisted:
  label: Unsichtbar
  text: Inhalte können von allen angesehen werden die den direkten Link kennen
listed:
  label: Sichtbar
  text: Inhalte können von allen angesehen werden
