#
# @info Default page statuses
# @path site/blueprints/status/default.yml
# @date 20220508
#

draft:
  label: Entwurf
  # text: Inhalte im Entwurfsmodus können nur von Panel-Benutzern angesehen werden.
unlisted:
  label: Unsichtbar
  # text: The article is online and can be visited with the direct URL.
listed:
  label: Sichtbar
  # text: The article is online and listed in the blog
